/**
 * My API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package gp.backend.model

import gp.backend.model.Queue

import com.squareup.moshi.Json

/**
 * 
 *
 * @param turnId 
 * @param position 
 * @param logoUrl 
 * @param state 
 * @param queue 
 */

data class BookedTurnQueue (

    @Json(name = "turnId")
    val turnId: kotlin.String? = null,

    @Json(name = "position")
    val position: kotlin.Int? = null,

    @Json(name = "logoUrl")
    val logoUrl: kotlin.String? = null,

    @Json(name = "state")
    val state: BookedTurnQueue.State? = null,

    @Json(name = "queue")
    val queue: Queue? = null

) {

    /**
     * 
     *
     * Values: aCTIVE,cANCELLED,cOMPLETED
     */
    enum class State(val value: kotlin.String) {
        @Json(name = "ACTIVE") aCTIVE("ACTIVE"),
        @Json(name = "CANCELLED") cANCELLED("CANCELLED"),
        @Json(name = "COMPLETED") cOMPLETED("COMPLETED");
    }
}

